# Generated by Django 5.0.3 on 2024-03-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dessert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=35)),
                ("country", models.CharField(max_length=35)),
                (
                    "additional_country",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
            ],
        ),
    ]
