# Generated by Django 5.0.3 on 2024-03-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dessert",
            name="featured_ingredient",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
