# Generated by Django 5.0.3 on 2024-03-13 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0003_dessert_additional_ingredient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dessert",
            name="additional_country",
        ),
    ]
