# Generated by Django 5.0.3 on 2024-03-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0004_remove_dessert_additional_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.IntegerField()),
                ("name", models.CharField(max_length=30)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Dessert",
        ),
    ]
