# Generated by Django 5.0.3 on 2024-03-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0005_student_delete_dessert"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=30)),
            ],
        ),
    ]
