# Generated by Django 5.0.3 on 2024-03-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0007_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="retirement_benefits",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
