# Generated by Django 5.0.3 on 2024-03-20 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataentry", "0008_employee_retirement_benefits"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="retirement_benefits",
            new_name="retirement",
        ),
    ]
